export const GET_ERRORS = 'GET_ERRORS';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const INIT_AUTH_REQUEST = 'INIT_AUTH_REQUEST';

export const END_AUTH_REQUEST = 'END_AUTH_REQUEST';

export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const LOGIN_ERROR = 'LOGIN_ERROR';

export const INIT_MODULE_REQUEST = 'INIT_MODULE_REQUEST';

export const GET_ALL_MODULES = 'GET_ALL_MODULES';

export const GET_SINGLE_MODULE = 'GET_SINGLE_MODULE';

export const MODULES_ERROR = 'MODULES_ERROR';

export const VERIFY_USER = 'VERIFY_USER';

export const GET_COMMUNITY_MESSAGES = 'GET_COMMUNITY_MESSAGES';

export const GET_COMMUNITY_MESSAGES_ERROR = 'GET_COMMUNITY_MESSAGES_ERROR';

export const LOADING = 'LOADING';

export const GET_TEST = 'GET_TEST';

export const TEST_ERROR = 'TEST_ERROR';

export const INIT_GET_TEST = 'INIT_GET_TEST';
export const GET_PROFILE = 'GET_PROFILE';

export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';

export const GET_PROFILE_FAILED = 'GET_PROFILE_FAILED';

export const UPLOAD_START = 'UPLOAD_START';

export const UPLOAD_SUCCESS = 'UPLOAD_SUCCESS';

export const UPLOAD_FAILED = 'UPLOAD_FAILED';

export const UPDATE_PROFILE_FAILED = 'UPDATE_PROFILE_FAILED';

export const PASSWORD_RESET_ERROR = 'PASSWORD_RESET_ERROR';

export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';

export const PASSWORD_CHANGE_SUCCESS = 'PASSWORD_CHANGE_SUCCESS';

export const PASSWORD_CHANGE_ERROR = 'PASSWORD_CHANGE_ERROR';
