export const GET_ERRORS = 'GET_ERRORS';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const INIT_AUTH_REQUEST = 'INIT_AUTH_REQUEST';

export const END_AUTH_REQUEST = 'END_AUTH_REQUEST';

export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const LOGIN_ERROR = 'LOGIN_ERROR';

export const INIT_MODULE_REQUEST = 'INIT_MODULE_REQUEST';

export const GET_ALL_MODULES = 'GET_ALL_MODULES';

export const GET_SINGLE_MODULE = 'GET_SINGLE_MODULE';

export const MODULES_ERROR = 'MODULES_ERROR';

export const VERIFY_USER = 'VERIFY_USER';

export const GET_COMMUNITY_MESSAGES = 'GET_COMMUNITY_MESSAGES';

export const GET_COMMUNITY_MESSAGES_ERROR = 'GET_COMMUNITY_MESSAGES_ERROR';
